LongClassNameCheck
l3r8yJ/sa-tan pull request #84
Opened 2023-12-28 13:56 UTC by h1alexbel

closes #81

2023-12-28 13:56 UTC, zoeself commented
@h1alexbel thank you for your Pull Request. I'll assign someone to review it soon. 

 If this PR solves a ``todo`` from the code, please don't forget to remove it.

2023-12-28 14:00 UTC, zoeself commented
@l3r8yJ please review this Pull Request. Deadline (when it should be merged or closed) is ``2023-12-31T14:00:20.904875``.

You should check if the requirements have been implemented (partially or in full), if there are unit tests covering the changes and if the CI build passes. Feel free to reject the PR or ask for changes if it's too big or not clear enough.

Estimation here is ``30 minutes``, that's how much you will be paid. You will be paid even if this PR gets rejected.

2023-12-28 15:45 UTC, l3r8yJ requested changes
@h1alexbel take a look at my comments below, please

2023-12-28 15:45 UTC, l3r8yJ commented on src/main/java/ru/l3r8y/ValidateMojo.java
> +    private int okClassNameLength = 13;
@h1alexbel i think this parameter can be configurable for each project, can you do it?

```xml
<maxClassNameLen>13<maxClassNameLen>
```

2023-12-28 15:51 UTC, l3r8yJ approved these changes
@h1alexbel looks good to me!

2023-12-28 16:01 UTC, l3r8yJ commented
@h1alexbel can you remove `pdd` GHA in this pr, looks like it's broken

2023-12-28 16:42 UTC, h1alexbel commented
@l3r8yJ I will fix it

2023-12-29 07:57 UTC, h1alexbel commented
@l3r8yJ take a look once again, please

2023-12-29 08:39 UTC, l3r8yJ commented
@rultor merge

2023-12-29 08:41 UTC, rultor commented
> @rultor merge 

@l3r8yj OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/37632-1871842404)

2023-12-29 08:43 UTC, merged

2023-12-29 08:44 UTC, rultor commented
> @rultor merge 

@l3r8yj Done! FYI, the full log is [here](https://www.rultor.com/t/37632-1871842404) (took me 3min)

2023-12-29 08:59 UTC, zoeself commented
@l3r8yJ thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).